package hook

type OnServerStartedInp struct {
	ApiApiDebug                    string `json:"api.apiDebug"`
	ApiSecret                      string `json:"api.secret"`
	FfmpegBin                      string `json:"ffmpeg.bin"`
	FfmpegCmd                      string `json:"ffmpeg.cmd"`
	FfmpegLog                      string `json:"ffmpeg.log"`
	GeneralMediaServerId           string `json:"general.mediaServerId"`
	GeneralAddMuteAudio            string `json:"general.addMuteAudio"`
	GeneralEnableVhost             string `json:"general.enableVhost"`
	GeneralFlowThreshold           string `json:"general.flowThreshold"`
	GeneralMaxStreamWaitMS         string `json:"general.maxStreamWaitMS"`
	GeneralPublishToHls            string `json:"general.publishToHls"`
	GeneralPublishToMP4            string `json:"general.publishToMP4"`
	GeneralPublishToRtxp           string `json:"general.publishToRtxp"`
	GeneralResetWhenRePlay         string `json:"general.resetWhenRePlay"`
	GeneralStreamNoneReaderDelayMS string `json:"general.streamNoneReaderDelayMS"`
	GeneralUltraLowDelay           string `json:"general.ultraLowDelay"`
	HlsFileBufSize                 string `json:"hls.fileBufSize"`
	HlsFilePath                    string `json:"hls.filePath"`
	HlsSegDur                      string `json:"hls.segDur"`
	HlsSegNum                      string `json:"hls.segNum"`
	HlsSegRetain                   string `json:"hls.segRetain"`
	HookAdminParams                string `json:"hook.admin_params"`
	HookEnable                     string `json:"hook.enable"`
	HookOnFlowReport               string `json:"hook.on_flow_report"`
	HookOnHttpAccess               string `json:"hook.on_http_access"`
	HookOnPlay                     string `json:"hook.on_play"`
	HookOnPublish                  string `json:"hook.on_publish"`
	HookOnRecordMp4                string `json:"hook.on_record_mp4"`
	HookOnRtspAuth                 string `json:"hook.on_rtsp_auth"`
	HookOnRtspRealm                string `json:"hook.on_rtsp_realm"`
	HookOnServerStarted            string `json:"hook.on_server_started"`
	HookOnShellLogin               string `json:"hook.on_shell_login"`
	HookOnStreamChanged            string `json:"hook.on_stream_changed"`
	HookOnStreamNoneReader         string `json:"hook.on_stream_none_reader"`
	HookOnStreamNotFound           string `json:"hook.on_stream_not_found"`
	HookTimeoutSec                 string `json:"hook.timeoutSec"`
	HttpCharSet                    string `json:"http.charSet"`
	HttpKeepAliveSecond            string `json:"http.keepAliveSecond"`
	HttpMaxReqCount                string `json:"http.maxReqCount"`
	HttpMaxReqSize                 string `json:"http.maxReqSize"`
	HttpNotFound                   string `json:"http.notFound"`
	HttpPort                       string `json:"http.port"`
	HttpRootPath                   string `json:"http.rootPath"`
	HttpSendBufSize                string `json:"http.sendBufSize"`
	HttpSslPort                    string `json:"http.sslport"`
	MulticastAddrMax               string `json:"multicast.addrMax"`
	MulticastAddrMin               string `json:"multicast.addrMin"`
	MulticastUdpTTL                string `json:"multicast.udpTTL"`
	RecordAppName                  string `json:"record.appName"`
	RecordFastStart                string `json:"record.fastStart"`
	RecordFileBufSize              string `json:"record.fileBufSize"`
	RecordFilePath                 string `json:"record.filePath"`
	RecordFileRepeat               string `json:"record.fileRepeat"`
	RecordFileSecond               string `json:"record.fileSecond"`
	RecordSampleMS                 string `json:"record.sampleMS"`
	RtmpHandshakeSecond            string `json:"rtmp.handshakeSecond"`
	RtmpKeepAliveSecond            string `json:"rtmp.keepAliveSecond"`
	RtmpModifyStamp                string `json:"rtmp.modifyStamp"`
	RtmpPort                       string `json:"rtmp.port"`
	RtpAudioMtuSize                string `json:"rtp.audioMtuSize"`
	RtpClearCount                  string `json:"rtp.clearCount"`
	RtpCycleMS                     string `json:"rtp.cycleMS"`
	RtpMaxRtpCount                 string `json:"rtp.maxRtpCount"`
	RtpVideoMtuSize                string `json:"rtp.videoMtuSize"`
	RtspAuthBasic                  string `json:"rtsp.authBasic"`
	RtspDirectProxy                string `json:"rtsp.directProxy"`
	RtspHandshakeSecond            string `json:"rtsp.handshakeSecond"`
	RtspKeepAliveSecond            string `json:"rtsp.keepAliveSecond"`
	RtspModifyStamp                string `json:"rtsp.modifyStamp"`
	RtspPort                       string `json:"rtsp.port"`
	RtspSslPort                    string `json:"rtsp.sslport"`
	ShellMaxReqSize                string `json:"shell.maxReqSize"`
	ShellPort                      string `json:"shell.port"`
}

type OnServerStartedOup struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
